---
title: Tom Byers
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
Twitter: https://twitter.com/ts_byers
LinkedIn: https://www.linkedin.com/in/tom-byers/
Github: https://github.com/tombyers
